FROM alpine:latest as builder

RUN apk update && \
    apk add wget unzip

RUN wget https://github.com/improbable-eng/grpc-web/releases/download/v0.14.0/grpcwebproxy-v0.14.0-linux-x86_64.zip && \
    unzip grpcwebproxy-v0.14.0-linux-x86_64.zip 

FROM alpine:latest

RUN apk update

COPY --from=builder dist/grpcwebproxy-v0.14.0-linux-x86_64 grpcwebproxy

EXPOSE 8080/tcp
EXPOSE 8080/udp

CMD [ \
    "/grpcwebproxy", \
    "--backend_tls_noverify", \
    "--use_websockets", \
    "--backend_tls=true", \
    "--allow_all_origins", \
    "--run_tls_server=false", \
    "--server_http_tls_port=$PORT", \
    "--server_http_max_read_timeout=60s", \
    "--backend_addr=beba-grpc-p2gh3d44pq-uc.a.run.app:443" \
]